### ISSUE TITLE
feature-request: spreadUpdate

### ISSUE THREAD

**Issue by cmanou** [andywer/squid#15]
It would be useful to have a spreadUpdate/set which could be used to generate dynamic update queries in a way that handles the undefined case. 

I am currently creating Patch Types as follows and would like a easy and type safe way to use these in update queries
```
export type PatchUserRecord = Partial<TableRow<typeof usersTable>>
```

**Comment by andywer** [comment]
Makes sense 👍

Quick question:
> that handles the undefined case

You mean that it supports any subset of the record's fields to be updated, right?

**Comment by cmanou** [comment]
@andywer yes, exactly that 👍

**Comment by andywer** [comment]
Added in [v0.4.0](https://github.com/andywer/squid/releases/tag/v0.4.0). Still needs to be added to postguard: andywer/postguard#27.

**Comment by andywer** [comment]
Follow-up: Postguard is updated, too. See [v0.2.0](https://github.com/andywer/postguard/releases/tag/v0.2.0).
