### ISSUE TITLE
Support for "IN" clauses

### ISSUE THREAD

**Issue by twk** [andywer/squid#35]
I might be missing it completely, but I don't see support in the library for running a query that uses an `IN` clause. Of course I could just generate that myself, but it would be nice to make sure it isn't vulnerable to any sql injection.

**Comment by andywer** [comment]
You can simply do

```js
sql`SELECT * FROM my_table WHERE id IN ${["id-1", "id-2", "id-3"]}`
```

😉

**Comment by twk** [comment]
Great, thank you!
